#!/usr/bin/env node
/**
 * Nexia CRM Template — interactive setup
 *
 * Collects tokens, writes .env.local, runs migrations on Supabase, seeds crm_config.
 *
 * Usage:
 *   npm run setup
 */
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const rl = createInterface({ input: stdin, output: stdout });
const ask = async (q, def = "") => {
  const suffix = def ? ` (${def})` : "";
  const a = (await rl.question(`${q}${suffix}: `)).trim();
  return a || def;
};
const pw = async (q) => {
  // Basic password mask — not TTY-perfect but hides typing
  stdout.write(q + ": ");
  return new Promise((resolve) => {
    let buf = "";
    stdin.setRawMode?.(true);
    stdin.resume();
    stdin.setEncoding("utf8");
    const onData = (ch) => {
      if (ch === "\n" || ch === "\r") {
        stdout.write("\n");
        stdin.setRawMode?.(false);
        stdin.removeListener("data", onData);
        stdin.pause();
        resolve(buf.trim());
      } else if (ch === "\u0003") process.exit(1);
      else if (ch === "\u007f") buf = buf.slice(0, -1);
      else {
        buf += ch;
        stdout.write("*");
      }
    };
    stdin.on("data", onData);
  });
};

console.log(`
╔══════════════════════════════════════════════════════╗
║  NEXIA CRM TEMPLATE — SETUP                         ║
║  Vai coletar tokens e preparar .env.local +          ║
║  Supabase schema + crm_config seeds.                 ║
╚══════════════════════════════════════════════════════╝
`);

// 1. Load existing .env.local if any
const envPath = ".env.local";
const existing = existsSync(envPath)
  ? Object.fromEntries(readFileSync(envPath, "utf8").split("\n").filter(Boolean).map((l) => {
      const idx = l.indexOf("=");
      return [l.slice(0, idx), l.slice(idx + 1).replace(/^"(.*)"$/, "$1")];
    }))
  : {};

// 2. Collect per-project secrets
console.log("\n── SUPABASE ──");
console.log("  Dashboard → Settings → API");
const SUPABASE_URL = await ask("NEXT_PUBLIC_SUPABASE_URL (https://xxx.supabase.co)", existing.NEXT_PUBLIC_SUPABASE_URL);
const SUPABASE_ANON = await ask("NEXT_PUBLIC_SUPABASE_ANON_KEY", existing.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const SUPABASE_SERVICE = await pw("SUPABASE_SERVICE_ROLE_KEY (hidden)");
console.log("  Dashboard → Project Settings → Database → Connection string (Pooler: Session mode)");
const DB_POOLER_HOST = await ask("DB Pooler host (aws-N-REGION.pooler.supabase.com)", existing.DB_POOLER_HOST || "aws-1-sa-east-1.pooler.supabase.com");
const DB_POOLER_USER = await ask("DB Pooler user (postgres.<project-ref>)", existing.DB_POOLER_USER);
const DB_PASSWORD = await pw("DB_PASSWORD (hidden)");

console.log("\n── UAZAPI (WhatsApp) ──");
const UAZAPI_URL = await ask("UAZAPI_URL (https://<instance>.uazapi.com)", existing.UAZAPI_URL);
const UAZAPI_TOKEN = await pw("UAZAPI_TOKEN (hidden)");

console.log("\n── ANTHROPIC ──");
const ANTHROPIC_API_KEY = await pw("ANTHROPIC_API_KEY (hidden)");

console.log("\n── GROQ (opcional — transcrição de áudios do backfill) ──");
const GROQ_API_KEY = await ask("GROQ_API_KEY (ENTER pra pular)", existing.GROQ_API_KEY || "");

console.log("\n── GOOGLE GEMINI (opcional — análise de sentimento) ──");
const GOOGLE_API_KEY = await ask("GOOGLE_API_KEY (ENTER pra pular)", existing.GOOGLE_API_KEY || "");

console.log("\n── ANTHROPIC ADMIN (opcional — mostra gasto no /crm/config) ──");
const ANTHROPIC_ADMIN_KEY = await ask("ANTHROPIC_ADMIN_KEY (sk-ant-admin-... ou ENTER pra pular)", existing.ANTHROPIC_ADMIN_KEY || "");

// 3. Generate webhook secret
const WEBHOOK_SECRET = existing.WEBHOOK_SECRET || randomBytes(32).toString("hex");
console.log(`\nGerando webhook secret: ${WEBHOOK_SECRET.slice(0, 16)}...`);

rl.close();

// 4. Write .env.local
const envLines = [
  "# Auto-generated by scripts/setup.mjs — re-run to regenerate",
  `NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON}`,
  `SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE}`,
  `DB_POOLER_HOST=${DB_POOLER_HOST}`,
  `DB_POOLER_USER=${DB_POOLER_USER}`,
  `DB_PASSWORD=${DB_PASSWORD}`,
  `UAZAPI_URL=${UAZAPI_URL}`,
  `UAZAPI_TOKEN=${UAZAPI_TOKEN}`,
  `ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}`,
  GROQ_API_KEY ? `GROQ_API_KEY=${GROQ_API_KEY}` : "",
  GOOGLE_API_KEY ? `GOOGLE_API_KEY=${GOOGLE_API_KEY}` : "",
  ANTHROPIC_ADMIN_KEY ? `ANTHROPIC_ADMIN_KEY=${ANTHROPIC_ADMIN_KEY}` : "",
  `WEBHOOK_SECRET=${WEBHOOK_SECRET}`,
].filter(Boolean);
writeFileSync(envPath, envLines.join("\n") + "\n");
console.log(`\n✓ ${envPath} gerado.`);

// 5. Run schema.sql via pooler
console.log("\n── Aplicando schema.sql no Supabase ──");
const { default: postgres } = await import("postgres");
const cs = `postgresql://${DB_POOLER_USER}:${encodeURIComponent(DB_PASSWORD)}@${DB_POOLER_HOST}:5432/postgres`;
const sql = postgres(cs, { ssl: "require", prepare: false, max: 1, connect_timeout: 30 });
try {
  const schema = readFileSync("supabase/schema.sql", "utf8");
  await sql.unsafe(schema);
  console.log("  ✓ schema.sql aplicado");
} catch (err) {
  console.error(`  ✗ falhou: ${err.message}`);
  console.error("  Verifique DB_POOLER_HOST / DB_POOLER_USER / DB_PASSWORD e tente rodar o schema manualmente em Supabase → SQL Editor.");
}

// 6. Seed webhook config
try {
  // NEXT_PUBLIC_APP_URL será setado manualmente após vercel deploy
  const appUrl = await (async () => "https://PLACEHOLDER.vercel.app")();
  await sql`
    insert into crm_config (key, value) values
      ('webhook_url', ${appUrl + "/api/leads/new"}),
      ('webhook_secret', ${WEBHOOK_SECRET})
    on conflict (key) do update set value = excluded.value, updated_at = now()
  `;
  console.log("  ✓ webhook_url / webhook_secret seedados em crm_config");
} catch (err) {
  console.warn(`  ⚠️ seed config falhou: ${err.message}`);
}

await sql.end();

console.log(`
╔══════════════════════════════════════════════════════╗
║  SETUP CONCLUÍDO                                     ║
╠══════════════════════════════════════════════════════╣
║  Próximos passos:                                    ║
║                                                      ║
║  1. Editar src/config/project.ts                     ║
║     (nome, persona, stages do kanban)                ║
║                                                      ║
║  2. Deploy:                                          ║
║     vercel --prod                                    ║
║                                                      ║
║  3. Atualizar webhook_url em crm_config:             ║
║     (no /crm/config após primeiro deploy)            ║
║                                                      ║
║  4. Acessar /crm/config pra ajustar prompt IA,       ║
║     modelo, intervals de disparo etc.                ║
╚══════════════════════════════════════════════════════╝
`);
